#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : videoproto
Version  : 2.3.3
Release  : 5
URL      : http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.3.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.3.tar.bz2
Summary  : Video extension headers
Group    : Development/Tools
License  : MIT-Opengroup
Requires: videoproto-doc
BuildRequires : pkgconfig(xorg-macros)

%description
X Video Extension
This extension provides a protocol for a video output mechanism,
mainly to rescale video playback in the video controller hardware.

%package dev
Summary: dev components for the videoproto package.
Group: Development
Provides: videoproto-devel

%description dev
dev components for the videoproto package.


%package doc
Summary: doc components for the videoproto package.
Group: Documentation

%description doc
doc components for the videoproto package.


%prep
%setup -q -n videoproto-2.3.3

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xv.h
/usr/include/X11/extensions/XvMC.h
/usr/include/X11/extensions/XvMCproto.h
/usr/include/X11/extensions/Xvproto.h
/usr/include/X11/extensions/vldXvMC.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/videoproto/*
