#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : videoproto
Version  : 2.3.3
Release  : 10
URL      : http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.3.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.3.tar.bz2
Summary  : Video extension headers
Group    : Development/Tools
License  : MIT-Opengroup
Requires: videoproto-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)

%description
X Video Extension
This extension provides a protocol for a video output mechanism,
mainly to rescale video playback in the video controller hardware.

%package dev
Summary: dev components for the videoproto package.
Group: Development
Provides: videoproto-devel

%description dev
dev components for the videoproto package.


%package dev32
Summary: dev32 components for the videoproto package.
Group: Default

%description dev32
dev32 components for the videoproto package.


%package doc
Summary: doc components for the videoproto package.
Group: Documentation

%description doc
doc components for the videoproto package.


%prep
%setup -q -n videoproto-2.3.3
pushd ..
cp -a videoproto-2.3.3 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
%configure --disable-static  --libdir=/usr/lib32
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xv.h
/usr/include/X11/extensions/XvMC.h
/usr/include/X11/extensions/XvMCproto.h
/usr/include/X11/extensions/Xvproto.h
/usr/include/X11/extensions/vldXvMC.h
/usr/lib64/pkgconfig/videoproto.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32videoproto.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/videoproto/*
